"""add data_source to monthly_company_metrics

Revision ID: 70f9c3ba31b8
Revises: 7b7e93bb0ac5
Create Date: 2026-07-20 16:44:56.814584
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '70f9c3ba31b8'
down_revision: str | None = '7b7e93bb0ac5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_company_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source', sa.String(length=16), nullable=False))
        batch_op.create_index(batch_op.f('ix_monthly_company_metrics_data_source'), ['data_source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_company_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_company_metrics_data_source'))
        batch_op.drop_column('data_source')

    # ### end Alembic commands ###
