"""initial schema

Revision ID: 7b7e93bb0ac5
Revises: 
Create Date: 2026-07-20 14:24:11.331882
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7b7e93bb0ac5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('career_site_url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_code'), ['code'], unique=True)

    op.create_table('role_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_family', sa.String(length=64), nullable=False),
    sa.Column('role_subfamily', sa.String(length=64), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_taxonomy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_taxonomy_role_family'), ['role_family'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('aliases_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('jobs_inserted', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_unchanged', sa.Integer(), nullable=False),
    sa.Column('jobs_closed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('key_source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('role_family', sa.String(length=64), nullable=True),
    sa.Column('role_subfamily', sa.String(length=64), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('experience_level', sa.String(length=64), nullable=True),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('workplace_type', sa.String(length=32), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=16), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('qualifications_text', sa.Text(), nullable=True),
    sa.Column('responsibilities_text', sa.Text(), nullable=True),
    sa.Column('posting_url', sa.Text(), nullable=False),
    sa.Column('source_posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('missed_crawls', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_job_id', name='uq_company_source_job')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_data_source'), ['data_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_role_family'), ['role_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_job_id'), ['source_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)

    op.create_table('monthly_company_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=False),
    sa.Column('closed_jobs', sa.Integer(), nullable=False),
    sa.Column('updated_jobs', sa.Integer(), nullable=False),
    sa.Column('technology_jobs', sa.Integer(), nullable=False),
    sa.Column('operations_jobs', sa.Integer(), nullable=False),
    sa.Column('risk_jobs', sa.Integer(), nullable=False),
    sa.Column('data_ai_jobs', sa.Integer(), nullable=False),
    sa.Column('top_skills_json', sa.JSON(), nullable=False),
    sa.Column('top_locations_json', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year_month', name='uq_company_month')
    )
    with op.batch_alter_table('monthly_company_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_company_metrics_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_company_metrics_year_month'), ['year_month'], unique=False)

    op.create_table('job_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('location_text', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_locations_job_id'), ['job_id'], unique=False)

    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skill')
    )
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_skills_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('job_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('changed_fields_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_snapshots_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_snapshots_job_id'))

    op.drop_table('job_snapshots')
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_job_skills_job_id'))

    op.drop_table('job_skills')
    with op.batch_alter_table('job_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_locations_job_id'))

    op.drop_table('job_locations')
    with op.batch_alter_table('monthly_company_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_company_metrics_year_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_company_metrics_company_id'))

    op.drop_table('monthly_company_metrics')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_role_family'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_active'))
        batch_op.drop_index(batch_op.f('ix_jobs_data_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_content_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_key'))

    op.drop_table('jobs')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_company_id'))

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_category'))
        batch_op.drop_index(batch_op.f('ix_skills_canonical_name'))

    op.drop_table('skills')
    with op.batch_alter_table('role_taxonomy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_taxonomy_role_family'))

    op.drop_table('role_taxonomy')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
