"""Analytics: metrics queries and deterministic narrative summaries.

Every number in a summary comes from a database query here — never invented,
never generated by a model. See summaries.py's module docstring for how the
narrative template works.
"""
